Controllers/CRUDController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol;
using StringConverter.Data;
using StringConverter.Data.Interfaces;
using StringConverter.Data.Repositories;
using StringConverter.Models.Domain;
using StringConverter.Models.Dto;
using StringConverter.Models.ViewModel;
using System;
using System.Net.Security;
using System.Text.Json;

namespace StringConverter.Controllers
{
    [Authorize]
    public class CRUDController : Controller
    {
        private readonly IStringConverterRepository _repository;
        private readonly ITranslateText _translate;

        public CRUDController( IStringConverterRepository repository ,ITranslateText translate) 
        {
            _repository = repository;
            _translate = translate; 
        }


        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }




        [HttpPost]
        [ActionName("Add")]
        public async Task<IActionResult?> Add(AddRequest addRequest)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var translate = await _translate.TranslateText(addRequest.InputText);
                    TblConvertString save = new TblConvertString()
                    {
                        DataField = translate,
                    };
                    _repository.Add(save);
                    return RedirectToAction(nameof(GetText));
                }
                //_logger.LogInformation("Model State is Invalid");

                return StatusCode(400, "Bad Request");
            }
            catch (Exception)
            {

                throw new ArgumentException("Error occured");
            }
        }

        [HttpGet]

        public async Task<IActionResult?> GetText()
        {
           
                var getData = new GetViewModel();
                FormattableString fetch = $"[dbo].[spcGetTranslatedText]";
                var gets = await _repository.GetAllAsync(fetch);             
                getData.TblConvertStrings = gets;
                if (getData is null)
                {
                return StatusCode(400, "Not Found");
                }
                return View(getData);
         
        }

        #region
        //[HttpPut]
        //public async Task<IActionResult> UpdateTranslator(Guid Id, UpdateDto update)
        //{
        //    try
        //    {
        //        if (!ModelState.IsValid)
        //        {
        //            return BadRequest();
        //        }
        //        var translatex = await _translate.TranslateText(update.DataField);
        //        var query = new TblConvertString()
        //        {
        //            UserIDpk = Id,
        //            DataField = translatex
        //        };
        //        var response = _repository.Update(query);
        //        return Ok(response);
        //    }
        //    catch (Exception ex)
        //    {

        //        Console.WriteLine("{0}",ex.Message);
        //    }
        //    return default;
        //}

        //[HttpDelete]

        //public async Task<IActionResult> Delete(Guid Id)
        //{
            
        //    var del =  _repository.Delete(Id);

        //    return Ok(del);
        //}
        #endregion
    }

}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StringConverter</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StringConverter.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.5/css/jquery.dataTables.css" />


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.13.5/js/jquery.dataTables.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="" asp-action="">StringConverter</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="CRUD" asp-action="Add">Add Text</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="CRUD" asp-action="GetText">DataTable</a>
                        </li> 
                        
                        @*<li class="nav-item">
                            <a class="nav-link text-light" asp-area="Identity" asp-page="~/Account/Login">Login</a>*@
                        </li>
                       <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
          
            </div>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - StringConverter - <a asp-area="" asp-controller="CRUD" asp-action="GetText">Show</a>
        </div>
    </footer>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>